# Generated by Django 4.1.13 on 2024-04-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='walet',
            field=models.FloatField(default=11),
        ),
    ]
