# Generated by Django 4.1.13 on 2024-04-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0006_remove_item_item_quantity'),
        ('ecomApp', '0002_alter_customuser_walet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_management.item'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='openingstock',
            field=models.IntegerField(default=0),
        ),
    ]
