# Generated by Django 4.1.13 on 2024-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0003_alter_stock_item_id_alter_stock_openingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
