# Generated by Django 4.1.13 on 2024-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0004_customuser_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
