# Generated by Django 4.1.13 on 2024-04-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0007_otp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercoupon',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
