# Generated by Django 4.1.13 on 2024-07-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0009_customuser_is_influencer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_influencer',
        ),
    ]
