# Generated by Django 4.1.13 on 2024-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0010_remove_customuser_is_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
