# Generated by Django 4.1.13 on 2024-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0011_customuser_is_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='influencer_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
