# Generated by Django 5.1.7 on 2025-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0012_customuser_influencer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
