# Generated by Django 5.1.7 on 2025-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0013_catagory_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
