# Generated by Django 5.2 on 2025-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0014_stock_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='piece_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
