# Generated by Django 4.2.5 on 2024-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
