# Generated by Django 4.2.5 on 2024-05-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_alter_influencer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
