# Generated by Django 4.1.13 on 2024-07-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_influencer_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='last_login',
        ),
    ]
