# Generated by Django 4.1.13 on 2024-07-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0009_influencer_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
