# Generated by Django 4.1.13 on 2024-07-14 08:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0010_remove_influencer_date_joined_influencer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
