# Generated by Django 4.1.13 on 2024-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0012_influencer_is_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
