# Generated by Django 4.1.13 on 2024-07-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0013_influencer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='otp_value',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.CreateModel(
            name='InfluencerOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='influencer.influencer')),
            ],
        ),
    ]
