# Generated by Django 4.1.13 on 2024-07-15 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0014_influencer_otp_value_influencerotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
