# Generated by Django 5.1.7 on 2025-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0017_influencerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
