# Generated by Django 5.1.7 on 2025-04-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0019_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='influenceramount',
            name='current_wallet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='current_wallet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
