# Generated by Django 5.1.7 on 2025-04-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0020_influenceramount_current_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
