# Generated by Django 5.2 on 2025-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0021_withdrawrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
