# Generated by Django 4.1.13 on 2024-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0002_item_item_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_measurement',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
