# Generated by Django 4.1.13 on 2024-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0003_alter_item_item_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_measurement',
            field=models.CharField(default='', max_length=10),
        ),
    ]
