# Generated by Django 4.1.13 on 2024-04-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0004_alter_item_item_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='makingprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
