# Generated by Django 4.1.13 on 2024-04-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0005_item_makingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
    ]
