# Generated by Django 4.1.13 on 2024-04-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0006_remove_item_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_measurement',
        ),
    ]
