# Generated by Django 4.1.13 on 2024-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0007_remove_item_item_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='veg',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
