# Generated by Django 4.1.13 on 2024-07-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0008_item_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='non_veg',
            field=models.BooleanField(default=False),
        ),
    ]
