# Generated by Django 5.1.7 on 2025-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0009_item_non_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
