# Generated by Django 5.2 on 2025-05-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0010_item_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='piece_count',
            field=models.IntegerField(default=0),
        ),
    ]
