# Generated by Django 5.2 on 2025-05-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0011_item_piece_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_barcode',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
    ]
