# Generated by Django 4.1.13 on 2024-07-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressadmin',
            name='admin',
        ),
    ]
