# Generated by Django 4.1.13 on 2024-07-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0002_alter_walet_wallet_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBenefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
