# Generated by Django 4.1.13 on 2024-07-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0003_purchasebenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebenefit',
            name='status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
