# Generated by Django 5.0.4 on 2024-07-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0004_alter_purchasebenefit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationBenefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralBenefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='1', max_length=50)),
            ],
        ),
    ]
