# Generated by Django 4.1.13 on 2024-07-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='percentage_benefit',
            field=models.FloatField(default=0.0),
        ),
    ]
