# Generated by Django 4.1.13 on 2024-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_percentage_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='influencer_code',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
